### PR TITLE
Python 3 support, Django 1.8 ~ 1.10

### LINKED ISSUE #6: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
Hi,

I got this error when I tried to export all rows (not fields)

Is this compatible with python3.4

python3/3.4.1/lib/python3.4/site-packages/admin_export/views.py in get_context_data
26: return dict(context.items() + field_data.items()) 

T.

### PR DESCRIPTION
**Pull request by fgmacedo**
This PR adds support for Python 3 (fixes #6) and  Django from 1.8 to 1.10.

Improves the test coverage to 86%. WIth tox to automated tests with all supported versions.

It depends on the related PR to `django-report-utils` (https://github.com/burke-software/django-report-utils/pull/27).

Please let me know if you need something else. I'm deploying a project using django-admin-export, so I can help to keep it up to date.

Best regards,

PS: Since it includes the changes from https://github.com/burke-software/django-admin-export/pull/10 and https://github.com/burke-software/django-admin-export/pull/11, i'm closing those PRs.

### CODE REVIEW

**Comment by bufke** [comment]
Would you be interested in maintaining this project? I no longer use it.

**Comment by fgmacedo** [comment]
Yeah, no problem. Since I'm using it, I can keep it up to date. So let me know how to proceed.

**Comment by bufke** [comment]
You are welcome to use this repo if you want, I can give you access. Or forking is fine too. Let me know.

**Comment by fgmacedo** [comment]
David, what about the `django-report-utils`, do you will keep It? Since It is a direct dependence, I'll need a new release including the changes on the PR that I sent to you.

I think that a fork or a new organization are the best options.

**Comment by fgmacedo** [comment]
There's another option, that is the repository transfer, so github will redirect the URLs to the new repo, including forks, issues, etc.. https://help.github.com/articles/about-repository-transfers/

Let me know.

**Comment by bufke** [comment]
Sorry I forgot about all this. `django-report-utils` exists because it shared code between this and django-report-builder. But since then I've dropped working on this project and moved all the functionality I needed into report builder itself. The short answer is no I don't use it at all.

Let me know if you need anything from me like transferring the repo. You are welcome to fork, keep the namespace as is, or transfer it.

**Comment by fgmacedo** [comment]
Hi, David!  How are you? Happy new year!

I did a fork for my use since I need It working on Python 3.5. I've also joined all required code into a single project, under this repo: https://github.com/fgmacedo/django-export-action

The new project is released on PyPI as `django-export-action`.

Please let me know if you are ok with this.

Best regards!

**Comment by bufke** [comment]
Sounds good - I'll put a note on the readme here.

**Pull request closed without merging**
